module "rds" {
  source = "terraform-aws-modules/rds/aws"

  identifier = "${var.name}-${var.environment}-rds-coach8-3"

  engine              = var.db_engine
  engine_version      = var.db_engine_version
  instance_class      = var.db_instance_class
  allocated_storage   = var.db_allocated_storage
  storage_type        = var.db_storage_type
  storage_encrypted   = false
  multi_az            = false
  publicly_accessible = false
  # MySQL DBName must start with a letter and be alphanumeric only —
  # no hyphens or underscores, so var.name ("alex-tf") can't be used here.
  db_name  = "alextfDBcoach8"
  username = var.db_username
  port     = var.db_port

  # Master password is generated by AWS and stored in Secrets Manager.
  # Nothing is written to code or state.
  manage_master_user_password = true

  #iam_database_authentication_enabled = true

  vpc_security_group_ids = [module.rds_security_group.id]


  tags = {
    Name = "${var.name}-${var.environment}-rds-coach8-3"
  }

  create_db_subnet_group = true
  subnet_ids             = [data.aws_subnet.db1_selected.id, data.aws_subnet.db2_selected.id]

  # DB parameter group
  family = "mysql8.0"

  # DB option group
  major_engine_version = "8.0"

  # Database Deletion Protection
  # Set to false to allow `terraform destroy`. Turn back on for anything
  # you don't want to lose to an accidental destroy.
  deletion_protection = false

  # No final snapshot on delete. Fine for a coaching exercise — for real
  # data, leave this false so RDS captures a snapshot before deleting.
  skip_final_snapshot = true

  parameters = [
    {
      name  = "character_set_client"
      value = "utf8mb4"
    },
    {
      name  = "character_set_server"
      value = "utf8mb4"
    }
  ]
}


module "rds_security_group" {
  source = "terraform-aws-modules/security-group/aws"

  name        = "${var.name}-${var.environment}-sg-rds-coach8-3"
  description = "Security group for ${var.name}-${var.environment}-rds-coach8-3"
  vpc_id      = data.aws_vpc.selected.id

  ingress_rules = {
    mysql = {
      description                  = "allow ec2 security"
      from_port                    = 3306
      to_port                      = 3306
      ip_protocol                  = "tcp"
      referenced_security_group_id = module.ec2_security_group.id
    }
    # Redundant for a single non-clustered instance; re-enable for
    # Multi-AZ clusters or read replicas that need to talk to each other.
    # self-all = {
    #   ip_protocol                  = "-1"
    #   referenced_security_group_id = "self"
    #   description                  = "All traffic from members of this SG"
    # }
  }

  egress_rules = {
    all = {
      ip_protocol = "-1"
      cidr_ipv4   = "0.0.0.0/0"
    }
  }

  tags = {
    Terraform   = "true"
    Environment = var.environment
  }
}

